<a href="https://colab.research.google.com/github/Dahmani2020/DataAnalysis/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install fg-data-profiling pandas numpy --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 26.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 3.7 MB/s eta 0:00:00

In [2]:
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
from google.colab import files

In [3]:
uploaded = files.upload()

Saving marketing_campaign_data_messy.csv to marketing_campaign_data_messy.csv

In [5]:
df = pd.read_csv('marketing_campaign_data_messy.csv')

In [6]:
profile = ProfileReport(df, title = "Profiling Report", explorative = True)
profile.to_file('report.html')
files.download('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
 17%|█▋        | 2/12 [00:00<00:00, 16.81it/s]
 42%|████▏     | 5/12 [00:00<00:00, 18.98it/s]
100%|██████████| 12/12 [00:00<00:00, 27.78it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.head(10)

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
5,CMP-00006,Q4_BlackFriday_CMP-00006,2023-10-15 00:00:00,2023-10-28,Instagram,83386,2643,2697.03,NaN,1,NaN,IN
6,CMP-00007,Q3_Launch_CMP-00007,2023-10-07 00:00:00,2023-10-23,Facebook,38194,1135,1232.76,178.0,Yes,NaN,FA
7,CMP-00008,Q4_Launch_CMP-00008,2023-05-23,2023-05-28,Instagram,88498,1173,865.7,127.0,1,NaN,IN
8,CMP-00009,Q4_BlackFriday_CMP-00009,2023-03-23 00:00:00,2023-04-01,Google Ads,45131,1179,1046.18,104.0,1,NaN,GO
9,CMP-00010,Q2_Winter_CMP-00010,2023-03-21 00:00:00,2023-04-01,Email,61263,1153,1623.56,NaN,0,NaN,EM

# ====================================================
# STEP 1 : Header Cleaning
# ====================================================

In [9]:
print(df.columns.tolist())

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']

In [11]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns.tolist())

['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel', 'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks', 'campaign_tag']

# ====================================================
# STEP 2 : TYPE CONVERSION & CURRENCY CLEANING
# ====================================================

In [12]:
dirty_spend_mask = df['spend'].astype(str).str.contains(r'\$')
print(df.loc[dirty_spend_mask,['campaign_id','spend']].head(10))

   campaign_id     spend
0    CMP-00001   $102.82
21   CMP-00022   $2428.4
22   CMP-00023  $4726.22
31   CMP-00032  $2759.35
32   CMP-00033  $2393.02
36   CMP-00037  $2136.63
37   CMP-00038  $1118.15
40   CMP-00041   $205.48
53   CMP-00054   $919.99
55   CMP-00056  $3219.35

In [13]:
df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex=True)
df['spend'] = pd.to_numeric(df['spend'])
print(df.loc[dirty_spend_mask,['campaign_id','spend']].head(10))

   campaign_id    spend
0    CMP-00001   102.82
21   CMP-00022  2428.40
22   CMP-00023  4726.22
31   CMP-00032  2759.35
32   CMP-00033  2393.02
36   CMP-00037  2136.63
37   CMP-00038  1118.15
40   CMP-00041   205.48
53   CMP-00054   919.99
55   CMP-00056  3219.35

# ==================================================
# STEP 3 : CATEGORICAL TYPES
# ==================================================

In [14]:
print(df['channel'].unique())

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' 'E-mail' nan 'Gogle'
 'Tik_Tok' 'Facebok' 'Insta_gram']

In [19]:
cleanup_map = {
    'Facebok' : 'Facebook',
    'Insta_gram' : 'Instagram',
    'Gogle' : 'Google Ads',
    'Tik_Tok' : 'TikTok',
    'E-mail' : 'Email',
    'N/A' : np.nan
}

df['channel'] = df['channel'].replace(cleanup_map)
print(df['channel'].unique())

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' nan]

# ==================================================
# STEP 4 : HANDLING MIXED BOOLEANS
# ==================================================

In [20]:
print(df['active'].unique())

['Y' '0' 'No' 'True' 'Yes' '1' 'False']

In [23]:
bool_map = {
    'Y' : True,
    'Yes' : True,
    '1': True,
    1 : True,
    'No' : False,
    '0' : False,
    0 : False
}

df['active'] = df['active'].map(bool_map).fillna(False).astype(bool)
print(df['active'].unique())

[ True False]

/tmp/ipykernel_917/2073818697.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['active'] = df['active'].map(bool_map).fillna(False).astype(bool)

# ==================================================
# STEP 5 : DATE PARSING
# ==================================================

In [24]:
print(df['start_date'].dtype)

object

In [26]:
df['start_date'] = pd.to_datetime(df['start_date'], errors = 'coerce')
df['end_date'] = pd.to_datetime(df['end_date'], dayfirst = True, errors = 'coerce')
print(df['start_date'].dtype)
print(df['end_date'].dtype)

datetime64[ns]
datetime64[ns]

/tmp/ipykernel_917/3416517379.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date'] = pd.to_datetime(df['end_date'], dayfirst = True, errors = 'coerce')

In [33]:
df = df.loc[:, ~df.columns.duplicated()] # eliminate a duplicate column

In [35]:
df.head(10)

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA
5,CMP-00006,Q4_BlackFriday_CMP-00006,2023-10-15,2023-10-28,Instagram,83386,2643,2697.03,NaN,True,IN
6,CMP-00007,Q3_Launch_CMP-00007,2023-10-07,2023-10-23,Facebook,38194,1135,1232.76,178.0,True,FA
7,CMP-00008,Q4_Launch_CMP-00008,NaT,2023-05-28,Instagram,88498,1173,865.70,127.0,True,IN
8,CMP-00009,Q4_BlackFriday_CMP-00009,2023-03-23,2023-04-01,Google Ads,45131,1179,1046.18,104.0,True,GO
9,CMP-00010,Q2_Winter_CMP-00010,2023-03-21,2023-04-01,Email,61263,1153,1623.56,NaN,False,EM

# ==================================================
# STEP 6 : LOGICAL INTEGRITY (Clicks Vs Impressions)
# ==================================================

In [36]:
impossible_mask = df['clicks'] > df['impressions']
print(df.loc[impossible_mask,['campaign_id','clicks','impressions']].head(5))

Empty DataFrame
Columns: [campaign_id, clicks, impressions]
Index: []

# ==================================================
# STEP 7 : LOGICAL INTEGRITY (Time Travel)
# ==================================================

In [38]:
time_travel_mask = df['end_date'] < df['start_date']
print(df.loc[time_travel_mask,['campaign_id','start_date','end_date']].head(5))

    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-05-01
54    CMP-00055 2023-09-01 2023-08-27
71    CMP-00072 2023-02-01 2023-01-27
156   CMP-00157 2023-12-06 2023-12-01
200   CMP-00201 2023-01-11 2023-01-06

In [39]:
df.loc[time_travel_mask, 'end_date'] = df.loc[time_travel_mask, 'start_date'] + pd.Timedelta(days = 30)
print(df.loc[time_travel_mask,['campaign_id','start_date','end_date']].head(5))

    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-06-05
54    CMP-00055 2023-09-01 2023-10-01
71    CMP-00072 2023-02-01 2023-03-03
156   CMP-00157 2023-12-06 2024-01-05
200   CMP-00201 2023-01-11 2023-02-10

# ==================================================
# STEP 8 : HANDLING OUTLIERS
# ==================================================

In [42]:
Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3 - Q1
upper_limit = Q3 + (3 * IQR)

outlier_mask = df['spend'] > upper_limit
print(df.loc[outlier_mask,['campaign_id','spend']].head(5))

df.loc[outlier_mask, 'spend'] = upper_limit
print(df.loc[outlier_mask,['campaign_id','spend']].head(5))

     campaign_id      spend
789    CMP-00790  500000.00
1443   CMP-01444    8921.51
1460   CMP-01461  500000.00
1718   CMP-01719  500000.00
1754   CMP-01755  500000.00
     campaign_id      spend
789    CMP-00790  8603.5375
1443   CMP-01444  8603.5375
1460   CMP-01461  8603.5375
1718   CMP-01719  8603.5375
1754   CMP-01755  8603.5375

# ==================================================
# STEP 9 : STRING PARSING
# ==================================================

In [45]:
print(df['campaign_name'].head(10))

df['season'] = df['campaign_name'].str.extract(r'Q\d_([^_]+)_')
print(df[['campaign_name','season']].head(10))

0         Q4_Summer_CMP-00001
1         Q1_Launch_CMP-00002
2         Q3_Winter_CMP-00003
3    Q1_BlackFriday_CMP-00004
4         Q2_Winter_CMP-00005
5    Q4_BlackFriday_CMP-00006
6         Q3_Launch_CMP-00007
7         Q4_Launch_CMP-00008
8    Q4_BlackFriday_CMP-00009
9         Q2_Winter_CMP-00010
Name: campaign_name, dtype: object
              campaign_name       season
0       Q4_Summer_CMP-00001       Summer
1       Q1_Launch_CMP-00002       Launch
2       Q3_Winter_CMP-00003       Winter
3  Q1_BlackFriday_CMP-00004  BlackFriday
4       Q2_Winter_CMP-00005       Winter
5  Q4_BlackFriday_CMP-00006  BlackFriday
6       Q3_Launch_CMP-00007       Launch
7       Q4_Launch_CMP-00008       Launch
8  Q4_BlackFriday_CMP-00009  BlackFriday
9       Q2_Winter_CMP-00010       Winter